
- name: Install Vault
  hosts: all
  strategy: free
  become: true
  tasks:
    - name: ping hosts
      ping:
    - name: Download Vault binary
      unarchive:
        src: "https://releases.hashicorp.com/vault/1.4.0/vault_1.4.0_linux_amd64.zip"
        dest: /tmp
        remote_src: yes