language: python
python:
  - "2.7"

sudo: required

env:
  global:
    # ARTIFACTORY_API_KEY
    secure: "zPXLR5lq5j5wXAupZmxVYWlkJsprRiy+UAxT9LxXNEuXjcmwyyv9e8cvQ3t9cZ/qCL+kR1EFDJfEMCUf5EEwurlnRoh8QYv0ZGGXfXr5bJNlwcVEz3e9ZUHoKjXmZ+vRA21H3FVrYQA4XyBFvPmfWdCe6NQHaHxxTTt9yKMYVgwQKLUOWPv78E7pdy6LVOo+j3mnRnQ+gjC7k1mQdxD2iglRh/KAJ2TnUkkO5ABrgz/Q//n88SXKEwR8BJY64R2PFlxJBrIBxLP07i/3CstncPtAzLpmCjMJyPLHrqcJ6TruQ0ag9nqUgfZVyWd6JnEbFhCETParSrjPEz/CPNJMo0LUAi5nuC3pxCLDSMunc777Zpl0WZuYOpHm5hg9jviZiCiLwR7iEbLdgYzT4rRErn1OMV86P8qDtCZeo3/MAG3+QICvDI1H0OjUHJrfSGmU+opU8X0Dljjbeki+HOmuZCilHUylpMUpV3TSRVsrMLS0ck29zUUQsnxAj+wZvmj0NaCvOItVNugkGUbHoWQ1UcjUEmTTHP8XBV+ItB8/jzv7XLjk65gFrnCHRuddmspQbvhv5hIJ96welw8IIfLZl+sJXsKxjyLOnBheo8cwz07oC/k1UeFInBtrLM6qZxVVNrP/BGdxmheXoL/1FcjxtHYLbmLe6rss8AhxGLxUkSU="

script:
  - bash build/zip_csar.sh


before_deploy:
  - "bash ./build/pre_bintray_release.sh"

deploy:
  - provider: script
    script: bash build/deploy_artifactory.sh
    on:
      all_branches: true
    skip_cleanup: true

  
  - provider: bintray
    file: "build/bintray_release.json"
    user: "loicalbertin"
    key: 
      secure: "rEKazS5w7wsijy5n+BI+sLbLdXM2zKsPCRLzgZ+XdRCYjNcaWmQZ7LDP+4s2kAv0pi+fELtRT5AE5TiUU5Kh5SHLPJ9sOBhIbVsuaOHctUI2v4MCfdfiDNJF8SkG03yxUUA8jyb+8KfPJ6lSHd7VqtF0Nbpl56m5QkTICy5YdEEZYjUD4bwzBCTbndTa/5MAWTTO60aePHStW2gHMtgEGvnfqiEKYxSaZnONqgiqBLfW4JuLFbXnHlFJNoRMt6+XnZZAgjpYxpwsTbSqa46xBgPFGIkjO0Q6jIeCp7yBQCjRbHCNQ99lFV3qFem2o//U5rclm7FR0/8WeNL2THF1cUzd/nOVL4FZT3UeOW/f7ooyjDZ1poIkUe4C0tL5RlNixLMsia4+CWqP96fhcR9KtDBoP96ZjMcoQJ0RTyMFF9cJmsWyREhGWa/S/QUYXWnvpbiuEFoMuMlq2gJs0k+wNs9VbqB3t0jois7BI1o9BOu1/8HyNBo2YmQKZ7Zu51fcs1tDbVHjUCtnf1dbeXMEHlPc0Hb82LirmgLzWBTw3oqRC7gFJbOfANvgBXczT5QYct3CMu8xxiRNn+v6oELzCJCnk0rOjLK4BBgxtomN+5DgR8m/uIyj3kAqBIyh/f+px6gYlsQF2ZX563QX5b7c8jSP3zbGuJ66lrAvnRsNBMY="
    skip_cleanup: true
    on:
      tags: true

addons:
  apt:
    packages:
    - jq
