tosca_definitions_version: alien_dsl_2_0_0

#
# Ystia Forge
# Copyright (C) 2018 Bull S. A. S. - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.
#

metadata:
  template_name: org.ystia.mongodb.linux.ansible
  template_version: 2.0.0-SNAPSHOT
  template_author: Ystia

description: MongoBD Component

imports:
  - tosca-normative-types:1.0.0-ALIEN20
  - yorc-types:1.0.0
  - org.ystia.common:2.0.0-SNAPSHOT
  - org.ystia.mongodb.pub:2.0.0-SNAPSHOT

node_types:
  org.ystia.mongodb.linux.ansible.nodes.MongoDB:
    description: MongoDB component for linux
    tags:
      icon: /images/mongodb.jpg
    properties:
      root_password:
        type: string
        description: DBMS root password
        default: "mongodb"
        required: false
      port:
        type: integer
        description: DBMS port
        default: 3306
        constraints:
          - equal: 3306
      component_version:
        type: version
        description: The optional MongoDB component’s version.
        default: 3.6
        constraints:
          - equal: 3.6
    capabilities:
      host:
        type: org.ystia.mongodb.pub.capabilities.Container.MongoDB
     interfaces:
      Standard:
        create:
          description: MongoDB installation step
          implementation: playbooks/mongodb_install.yaml


