#
# Copyright 2018 Bull S.A.S. Atos Technologies - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Install Yorc
  hosts: all
  strategy: free
  become: true
  become_method: sudo
  tasks:
    - name: Setup permissions on temp dir
      file:
        path: "/tmp/yorc.d"
        state: directory
        mode: "u=rwx,g=rwx,o=rx"
    - name: Get hostname
      shell: echo $HOSTNAME
      register: result
    - set_fact:
        server_id: "{{ result.stdout }}"
    - name: Yorc config
      template: 
        src: config.yorc.yaml.j2
        dest: "/tmp/yorc.d/01.config.yorc.yaml"
        mode: "u=rw,g=rw,o=r"
    - name: Assemble config file
      assemble:
        src: /tmp/yorc.d/
        dest: '{{CONFIG_DIR}}/config.yorc.yaml'
        owner: yorc
        group: yorc
        mode: "u=rw,g=rw,o=r"
    - name: Delete config fragment directory
      file:
        path: /tmp/yorc.d/
        state: absent

    - name: "Ensures {{ DATA_DIR }}/.ssh dir exists"
      file:
        path: "{{ DATA_DIR }}/.ssh"
        state: directory
        owner: yorc
        group: yorc

    - name: "Copy key pair"
      copy:
        content: "{{ SSH_KEY }}"
        dest: "{{ DATA_DIR }}/.ssh/yorc.pem"
        owner: yorc
        group: yorc
        mode: 0400

    - name: "Copy certificate authority"
      copy:
        content: "{{ CA_PEM }}"
        dest: "{{ CONFIG_DIR }}/yorc_server_ca.pem"
        owner: yorc
        group: yorc
        mode: 0400
      when: REST_API_PROTOCOL == "https"

    - name: "Copy certificate authority private key"
      copy:
        content: "{{ CA_KEY }}"
        dest: "{{ CONFIG_DIR }}/yorc_server_ca.key"
        owner: yorc
        group: yorc
        mode: 0400
      when: REST_API_PROTOCOL == "https"

- name: Generate keys and certificates
  hosts: all
  strategy: free
  become: true
  become_user: yorc
  become_method: sudo
  tasks:
    - name: Generate an OpenSSL private key with default values (4096 bits, RSA).
      openssl_privatekey:
        path: "{{ CONFIG_DIR }}/yorc_server.key"
      when: REST_API_PROTOCOL == "https"

    - name: Get Host private IP address for which TLS connections are accepted
      set_fact:
        subjectAltName: "{{ IP_ADDRESS }}"
      when: REST_API_PROTOCOL == "https"
      
    - name: Generate an OpenSSL CSR with subjectAltName
      openssl_csr:
        path: "{{ CONFIG_DIR }}/yorc_server.csr"
        privatekey_path: "{{ CONFIG_DIR }}/yorc_server.key"
        subjectAltName: 'IP:{{ subjectAltName }},IP:127.0.0.1,DNS:localhost'
      when: REST_API_PROTOCOL == "https"

    - name: Generate an OpenSSL certificate
      openssl_certificate:
        path: "{{ CONFIG_DIR }}/yorc_server.pem"
        csr_path: "{{ CONFIG_DIR }}/yorc_server.csr"
        ownca_path: "{{ CONFIG_DIR }}/yorc_server_ca.pem"
        ownca_privatekey_path: "{{ CONFIG_DIR }}/yorc_server_ca.key"
        ownca_privatekey_passphrase: "{{ CA_PASSPHRASE }}"
        provider: ownca
        subjectAltName: 'IP:{{ subjectAltName }},IP:127.0.0.1,DNS:localhost'
      when: REST_API_PROTOCOL == "https"
