#
# Copyright 2019 Bull S.A.S. Atos Technologies - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


- name: Configure Google secrets
  hosts: all
  strategy: free
  become_user: yorc
  become: true
  tasks:
    - name: Get vault token
      shell: "echo {{ TOKEN_ENCRYPTED }} | openssl enc -d -aes256 -base64  -pass pass:{{ PASSPHRASE }}"
      register: tokenDecrypted
    - name: Set Vault scheme to https
      set_fact:
        vault_scheme: "https"
      when: TLS_DISABLED == "false"
    - name: Set Vault scheme to http
      set_fact:
        vault_scheme: "http"
      when: TLS_DISABLED == "true"

    - name: create temporary directory
      tempfile:
        state: directory
        suffix: gcredsdir
      register: tempdir
    - name: "Create temporary service account key file {{ CONFIG_DIR }}/creds.json"
      copy:
        content: "{{ CREDENTIALS }}"
        dest: "{{ tempdir.path }}/creds.json"
        mode: 0700

    - name: Create secrets
      shell: "vault kv put /secret/yorc/google credentials=@{{ tempdir.path }}/creds.json"
      environment:
          NO_PROXY: "{{ SERVER_ADDRESS }}"
          VAULT_TOKEN: "{{ tokenDecrypted.stdout_lines[0] }}"
          VAULT_ADDR: "{{ vault_scheme }}://{{ SERVER_ADDRESS }}:{{ SERVER_PORT }}"
          VAULT_CACERT: "{{ CONFIG_DIR }}/yorc_ca.pem"
          VAULT_CLIENT_CERT: "{{ CONFIG_DIR }}/yorc_server.pem"
          VAULT_CLIENT_KEY: "{{ CONFIG_DIR }}/yorc_server.key"

    - name: Remove temporary directory
      file:
        path: "{{ tempdir.path }}"
        state: absent
