#
# Copyright 2018 Bull S.A.S. Atos Technologies - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


- name: Setup AWS config
  hosts: all
  strategy: free
  become_user: yorc
  become: true
  vars:
    lock_file: "{{ CONFIG_DIR }}//config.lock"
  pre_tasks:
    - name: check for lock file
      wait_for:
        path: "{{ lock_file }}"
        state: absent
    - name: create lock file
      file:
        path: "{{ lock_file }}"
        state: touch
  tasks:
    - name: "get current config of Yorc"
      shell: "cat {{ CONFIG_DIR }}/config.yorc.yaml"
      register: result

    - set_fact:
        yorcConfig: "{{ result.stdout | from_yaml }}"
  
    - set_fact:
        tmp: '{ "infrastructures": { "aws": { "access_key": "ACCESS_KEY_YORC_SUBSTITUTION", "secret_key": "SECRET_KEY_YORC_SUBSTITUTION", "region": "{{ REGION }}" } } }'

    - set_fact:
        yorcConfig: "{{ yorcConfig | combine(tmp, recursive=True) }}"

    - name: "Output config to file {{ CONFIG_DIR }}/config.yorc.yaml"
      copy:
        content: "{{ yorcConfig | to_yaml }}"
        dest: "{{ CONFIG_DIR }}/config.yorc.yaml"

    - name: Set AWS secret access key
      replace:
        path: "{{ CONFIG_DIR }}/config.yorc.yaml"
        regexp: 'ACCESS_KEY_YORC_SUBSTITUTION'
        replace: "'{{ '{{' }} secret \"/secret/yorc/aws\" \"data=access_key\" | print {{ '}}' }}'"
      when: USE_VAULT == "true"
    - name: Set AWS access key
      replace:
        path: "{{ CONFIG_DIR }}/config.yorc.yaml"
        regexp: 'ACCESS_KEY_YORC_SUBSTITUTION'
        replace: "{{ ACCESS_KEY }}"
      when: USE_VAULT == "false"

    - name: Set AWS secret key from vault
      replace:
        path: "{{ CONFIG_DIR }}/config.yorc.yaml"
        regexp: 'SECRET_KEY_YORC_SUBSTITUTION'
        replace: "'{{ '{{' }} secret \"/secret/yorc/aws\" \"data=secret_key\" | print {{ '}}' }}'"
      when: USE_VAULT == "true"
    - name: Set AWS secret key
      replace:
        path: "{{ CONFIG_DIR }}/config.yorc.yaml"
        regexp: 'SECRET_KEY_YORC_SUBSTITUTION'
        replace: "{{ SECRET_KEY }}"
      when: USE_VAULT == "false"
  post_tasks:
    - name: remove lock file
      file:
        path: "{{ lock_file }}"
        state: absent
