
- name: Configure Vault
  hosts: all
  strategy: free
  become: yes
  become_user: vault
  become_method: sudo
  tasks:
    - name: Create Vault configuration file
      template:
        src: "config.vault.hcl.j2"
        dest: "{{ CONFIG_DIR }}/config.vault.hcl"
        owner: vault
        group: vault
        mode: 0770
